title: "Next.jsの考え方"
summary: "筆者なりに、Next.js(App Router)における設計思想やベストプラクティスをまとめました。"
topics: ["nextjs", "react"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro
  - data_fetch
  - data_mutation
  - static_dynamic_rendering
  - parallel_data_fetch
  - router_cache
  - composite_pattern
  - presentational_container_pattern
  - suspense_and_streaming
  - micro_api_design
  - use_data_loader
  - cache_tag_design
  - partial_pre_rendering
  - tips
